# Generated by Django 5.2.5 on 2025-09-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvilEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=30)),
                ('text_entry', models.CharField(max_length=1000)),
            ],
        ),
    ]
