# Generated by Django 5.2.5 on 2025-09-04 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evil', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvilEntry',
            new_name='EvilEntity',
        ),
    ]
