# Generated by Django 5.2.5 on 2025-09-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evil', '0002_rename_evilentry_evilentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='evilentity',
            name='image',
            field=models.ImageField(default='media\\default.png', upload_to='entity_image'),
        ),
    ]
