# Generated by Django 5.2.5 on 2025-09-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evil', '0003_evilentity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evilentity',
            name='image',
            field=models.ImageField(default='media\\default.png', upload_to='media/entity_image'),
        ),
    ]
