# Generated by Django 5.2.5 on 2025-09-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evil', '0005_alter_evilentity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='evilentity',
            name='image_alt_text',
            field=models.CharField(default='alt val', max_length=50),
            preserve_default=False,
        ),
    ]
