# Generated by Django 5.2.5 on 2025-09-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evil', '0006_evilentity_image_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evilentity',
            name='image_alt_text',
            field=models.CharField(max_length=100),
        ),
    ]
